name: Sphinx docs to gh-pages
on:
  release:
    types: [released]
  workflow_dispatch:

permissions:
  contents: write
jobs:
  sphinx_docs_to_gh-pages:
    runs-on: ubuntu-latest
    name: Sphinx docs to gh-pages
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python 3.9
        uses: actions/setup-python@v5
        with:
          python-version: 3.9
      - name: Installing the library
        shell: bash -l {0}
        run: |
          pip install https://github.com/glencoesoftware/zeroc-ice-py-linux-x86_64/releases/download/20240202/zeroc_ice-3.6.5-cp39-cp39-manylinux_2_28_x86_64.whl
          pip install .[docs]
      - name: Running Sphinx
        shell: bash -l {0}
        run: |
          cd docs/sphinx
          sphinx-apidoc -f -o source ../../ezomero test
          sphinx-build -b html source ../
      - name: Deploy to pages
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: docs
          branch: "documentation"