name: Release to PyPI

on:
  release:
    types: [released]

jobs:
  release:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
          python-version: '3.9'
    - name: Install Tools
      run: |
        python -mpip install build
        python -m build
    - name: Publish distribution to PyPI
      uses: pypa/gh-action-pypi-publish@v1
      with:
        password: ${{ secrets.PYPI_API_TOKEN }}
